module.exports = [
  'ACC file code',
  'Accession note',
  'AxesOrient/clock: reverse',
  'Card information',
  'Cataloging notes',
  'CD id',
  'Collection type',
  'Component prep comments',
  'Condition notes',
  'Conservation notes',
  'Control possible',
  'Cultural modification note',
  'Curatorial remarks',
  'Data entry notes',
  'Data error',
  'Deaccession notes',
  'Denomination',
  'Destructive sampling notes',
  'Inventory remarks',
  'Loan notes',
  'Minting',
  'NAGPRA archaeological evidence',
  'NAGPRA background statement',
  'NAGPRA bioevaluation data',
  'NAGPRA inventory collection history',
  'NAGPRA inventory consultation',
  'NAGPRA location comment',
  'NAGPRA research comments',
  'NAGPRA updated curation summary',
  'NSF grant osteology data',
  'NSF recataloging data',
  'Object count note',
  'Obverse type',
  'Original ledger comments',
  'Pathology notes',
  'Phase completed',
  'Photo roll',
  'Registration remark',
  'Researcher comments',
  'Reverse type',
  'Special collection',
  'Storage location notes',
  'Supplemental information',
  'TMS curatorial remarks',
  'TMS edition field',
  'Verbatim ledger'
];