module.exports = [
  'Audio recordings',
  'Casts and molds',
  'Cat.  1: California (archaeology and ethnology)',
  'Cat.  2 - North America (except Mexico and Central America)',
  'Cat.  3 - Mexico, Central America, and Caribbean Area',
  'Cat.  4 - South America (Uhle Collection)',
  'Cat.  5 - Africa (except the Hearst Reisner Egyptian Collection)',
  'Cat.  6 - Ancient Egypt (the Hearst Reisner Egyptian Collection)',
  'Cat.  7 - Europe (incl. Russia west of Urals, north of Caucasus)',
  'Cat.  8 - Classical Mediterranean regions',
  'Cat.  9 - Asia (incl. Russia east of Urals)',
  'Cat. 10 - Philippine Islands',
  'Cat. 11 - Oceania (incl. Australia)',
  'Cat. 13 - Photographic prints (without negatives)',
  'Cat. 15 - Photographic negatives',
  'Cat. 16 - South America (except Uhle Collection)',
  'Cat. 17 - Drawings and Paintings',
  'Cat. 18 - Malaysia (incl. Indonesia, excl. Philippine Islands)',
  'Cat. 22 - Rubbings of Greek & Latin Inscriptions',
  'Cat. 23 - No provenience (most of catalog deleted)',
  'Cat. 25 - Kodachrome color transparencies',
  'Cat. 26 - Motion picture film',
  'Cat. 28 - unknown (retired catalog)',
  'Cat. B - Barr collection',
  'Cat. Bascom',
  'Cat. E',
  'Cat. K - Kelly collection',
  'Cat. L - Lillard Collection',
  'Cat. NO',
  'Cat. TB',
  'Faunal Remains',
  'Human Remains',
  'Loans In',
  'Maps',
  'Mixed faunal and human remains',
  'Mounts',
  'NAGPRA-associated Funerary Objects',
  'Registration',
];