module.exports = [
  'Albert M. Bender Collection',
  'Bascom Collection',
  'Bennyhoff Olivella Shell Bead Collection',
  'Bernard-Murray Collection',
  'California Teaching Collection',
  'Collection of Photographs by Carleton E. Watkins, ca. 1874-1890',
  'Early Man Cast Points Collection',
  'Edra Moore Central California Archaeology Type Collection',
  'Edra Moore Study Collection',
  'Gifford Type Specimen Collection: California bones',
  'Gifford Type Specimen Collection: Shell',
  'Great Basin Teaching Kit',
  'Harner\'s Study Collection',
  'Juvenile Osteological Growth Series',
  'Malcolm Rogers ceramic type collection',
  'Meighan Historic Glass Bead Collection',
  'Mossman-Vitale Collection',
  'Niloufer Ichaporia (Hirschmann) collection',
  'Paleopathology Collection',
  'Panama Pacific International Exposition Collection',
  'Pilling Historic Artifact Collection',
  'Reisner\'s Egyptian Collection',
  'Richard Lerner collection',
  'Ronald Maduro collection',
  'Southwest Type Sherd Collection, Corrugated',
  'Treganza Clay Artifact Collection',
  'Uhle\'s Peruvian Collection'
];