module.exports = [
  'additional number',
  'attributed pahma number',
  'burial number',
  'moac subobjid',
  'museum number (recataloged to)',
  'previous number',
  'previous number (albert bender’s number)',
  'previous number (bascom’s number)',
  'previous number (collector\'s original number)',
  'previous number (design dept.)',
  'previous number (mvc number, mossman-vitale collection)',
  'previous number (ucas: university of california archaeological survey)',
  'song number',
  'tag',
  'temporary number',
  '(null)',
  'associated catalog number',
  'field number',
  'original number',
  'previous museum number (recataloged from)',
  'previous number (anson blake’s number)',
  'previous number (donor\'s original number)',
  'previous number (uc paleontology department)',
  'tb (temporary basket) number'
];