module.exports = [
  '(unknown)',
  'accession status unclear',
  'accessioned',
  'culturally affiliated',
  'culturally unaffiliated',
  'deaccessioned',
  'destroyed',
  'destructive analysis',
  'discarded',
  'exchanged',
  'intended for repatriation',
  'intended for transfer',
  'irregular Museum number',
  'missing',
  'missing in inventory',
  'not cataloged',
  'not located',
  'not received',
  'number not used',
  'object mount',
  'on loan (=borrowed)',
  'partially deaccessioned',
  'partially exchanged',
  'partially recataloged',
  'pending repatriation',
  'recataloged',
  'red-lined',
  'repatriated',
  'returned loan object',
  'sold',
  'stolen',
  'transferred'
];
